//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReqBlood
    {
        public int ReqId { get; set; }
        public string Title { get; set; }
        public string Msg { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public int GroupID { get; set; }
    
        public virtual BloodGroup BloodGroup { get; set; }
    }
}
